# Generated by Django 5.1.2 on 2024-10-27 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0002_alter_tweet_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweet',
            name='photo',
        ),
        migrations.AddField(
            model_name='tweet',
            name='email',
            field=models.EmailField(default='example@gmail.com', max_length=254),
        ),
    ]
