# Generated by Django 5.1.2 on 2024-10-27 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0003_remove_tweet_photo_tweet_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='email_status',
            field=models.CharField(default='ABC', max_length=20),
        ),
    ]
